- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes

  - name: update the repositories
    dnf:
      name: "*"
      state: latest
  
  - name: install httpd package
    dnf:
      name: httpd
  
  - name: start httpd service
    service:
      name: httpd
      state: started

  - name: add test webpage
    copy:
      content: "Hello from {{ ansible_host }} - Web server is up!"
      dest: /var/www/html/index.html
      mode: '0644'

  - name: allow traffic on port 80 in firewalld (RHEL)
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: reload firewalld to ensure changes apply
    command: firewall-cmd --reload

